Feature/notes
vitoriadz/Devideia pull request #10
Opened 2023-05-16 17:47 UTC by liviariegell

2023-05-21 16:12 UTC, nicolasscarvalho approved these changes

2023-05-21 16:15 UTC, leticiadutra22-23 approved these changes

2023-05-21 16:18 UTC, leticiadutra22-23 requested changes
a PR tem que ser pra dev não pra main, caso contrário causa conflito

2023-05-21 16:21 UTC, nicolasscarvalho requested changes
trocar o destino da branch main para develop

2023-05-23 13:25 UTC, vitoriadz approved these changes

2023-06-01 17:17 UTC, closed without merging